// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Persistence;

namespace Persistence.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20200321123049_SeedValues")]
    partial class SeedValues
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.2");

            modelBuilder.Entity("Domain.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Mail")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.Property<string>("Password")
                        .HasColumnType("TEXT");

                    b.Property<string>("Surname")
                        .HasColumnType("TEXT");

                    b.Property<string>("Username")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Mail = "mail1@ac.gr",
                            Name = "user1",
                            Password = "123456",
                            Surname = "surname1",
                            Username = "username1"
                        },
                        new
                        {
                            Id = 2,
                            Mail = "mail2@ac.gr",
                            Name = "user2",
                            Password = "123456",
                            Surname = "surname2",
                            Username = "username2"
                        },
                        new
                        {
                            Id = 3,
                            Mail = "mail3@ac.gr",
                            Name = "user3",
                            Password = "123456",
                            Surname = "surname3",
                            Username = "username3"
                        },
                        new
                        {
                            Id = 4,
                            Mail = "mail4@ac.gr",
                            Name = "user4",
                            Password = "123456",
                            Surname = "surname4",
                            Username = "username4"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
